# Generated by Django 5.1 on 2024-11-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('github', models.URLField()),
                ('deploy', models.URLField()),
                ('devchallenges', models.URLField()),
            ],
        ),
    ]
